### ISSUE TITLE
Have the ship shoot a projectile

### ISSUE THREAD

**Issue by paulshriner** [pwsdc/playdate-asteroids#4]
The projectile should come out the front of the ship. Spawn it under the ship (closer to the front, not in the center) so that it looks as though it was coming from the ship. Have the projectile move faster than the speed of the ship. It will need to account for direction, angle, etc. For now just have one button (left or right on d pad) press shoot the projectile. The projectile will continue until going off the screen, then it disappears (code from runner may be helpful here).

**Comment by DokKevin** [comment]
- [done] initialize game with certain number of projectiles 
    - 1 to start, this will allow us to allow multiple projectiles in the future if desired
    - I did it this way so that we don't have to worry about creating and destroying projectile objects all the time.
- [done] Use button callback function to activate a projectile (leftButtonDown, can be changed by changing the callback function to be used)
    - [done] Iterate over projectile table until we find one that isn't active, then activate it
    - [done] If no available projectiles, do nothing
- [done] Every update, update position of the projectile based on speed (1.5x ship movement to start, can be adjusted later)
    - [issue | done] discovered issue where rotating the ship while the projectile is on the screen also changes the direction of movement for the projectile. 
        - [resolution] Turns out that I was updating the projectile based on the direction of the ship and not the recorded direction of the projectile.
- [done] If projectile hits edge of screen, disappear
- [issue | done] if crank is docked, ship rotates with arrow keys, so pressing left both turns the ship left and fires a projectile
    - [resolution] if crank is docked, us A Button to fire
